### ISSUE TITLE
Make search of GHC more intellectual

### ISSUE THREAD

**Issue by atsky** [Atsky/haskell-idea-plugin#62]
Now plugin search ghc in PATH and /usr/local/bin. Make it more flexible.

**Comment by Koshub** [comment]
Please can you write what can I do to make plugin found path to ghc. I have installed Haskell platform and ghc in in the PATH, but I see this message on start IDE - ghc not found in PATH. It can cause issue. Please specify haskell SDK for project ....

**Comment by Atsky** [comment]
@Koshub, what OS are you using?

**Comment by Koshub** [comment]
OSX 10.10.2. Probably I have fixed it by adding symlink to /usr/local/bin from /Applications/ghc-7.8.4.app/Contents/bin. I think it is not so clear. Also too many things are not so clear too. I can't use the plugin because the configuration is like the walls-breaking. Sorry for this message, but I can't write a normal code for a whole day -  I have been trying to  configure the plugin. Can you please provide the step by step instructions, please? ))

**Comment by Atsky** [comment]
You should go to the `Project Structure`. Then add new GHC SDK.

![screen shot 2015-03-08 at 20 32 58](https://cloud.githubusercontent.com/assets/145728/6547222/5ac7f758-c5d2-11e4-97c9-a87b396e3cc2.png)

Then you should specify `/Applications/ghc-7.8.4.app/Contents/` as GHC home path
This should help.
